name: lsd_c
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py36_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - cuda90=1.0=h6433d27_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py_1
  - cython=0.29.17=py36he6710b0_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - expat=2.2.5=he1b5a44_1003
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - graphite2=1.3.13=h23475e2_0
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2019.4=243
  - ipdb=0.12.2=py_0
  - ipython=7.9.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.17.0=py36_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.17.1=h173b8e3_0
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.15=h516909a_1005
  - libopenblas=0.2.20=h9ac9557_7
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - matplotlib=3.1.1=py36h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mongodb=4.0.3=h597af5e_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.14.2=py36_nomklh2b20989_1
  - olefile=0.46=py36_0
  - openblas=0.3.4=h9ac9557_1000
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1g=h7b6447c_0
  - pandas=0.25.1=py36he6710b0_0
  - parso=0.7.0=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.2.2=py36_0
  - pixman=0.38.0=h7b6447c_0
  - prompt_toolkit=2.0.10=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pycocotools=2.0.0=py36h516909a_1000
  - pycparser=2.19=py36_0
  - pygments=2.6.1=py_0
  - pymongo=3.9.0=py36he6710b0_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36hcca6a23_4
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py_0
  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - pytz=2019.2=py_0
  - pyyaml=5.2=py36h7b6447c_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=h7b6447c_5
  - scipy=1.1.0=py36_nomklh9c1e066_0
  - seaborn=0.9.0=py36_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.10.1=py36hdd07704_0
  - tabulate=0.8.3=py36_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.0=py36_cu100
  - tornado=6.0.3=py36h516909a_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.9=py_0
  - wheel=0.33.4=py36_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - chardet==3.0.4
    - h5py==2.10.0
    - idna==2.8
    - importlib-resources==1.0.2
    - joblib==0.15.1
    - jsonpatch==1.24
    - jsonpointer==2.0
    - packaging==19.2
    - pyzmq==18.1.1
    - requests==2.22.0
    - scikit-learn==0.18.2
    - threadpoolctl==2.1.0
    - torchfile==0.1.0
    - torchnet==0.0.4
    - urllib3==1.25.7
    - visdom==0.1.8.9
    - websocket-client==0.56.0

